version: "3.8"

services: 
  postgresql:
    image: postgres:15
    ports: 
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
      